#!/usr/bin/env ruby

require 'csv'
require 'json'

# Read in the CSV data.
csv = CSV.parse(ARGF.read)

sanitized = csv.map { |row| row.map { |col| col.strip if col }}

# TODO: Filter unused values.

# Output the JSON representation of the data.
puts JSON.generate(sanitized)
