#!/usr/bin/env ruby

require 'csv'
require 'json'

# Read in the CSV data.
csv = CSV.parse(ARGF.read)

# TODO: Filter unused values.

# Output the JSON representation of the data.
puts JSON.generate(csv)
